### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by kodeine** [axiome-oss/django-initial-avatars#7]
Hello,
So im already storing avatars as a imagefield in profile model, how to make this package work, if image already exists dont create the initial avatar otherwise create the avatar.

Thanks

**Comment by b0bbywan** [comment]
You can either use if statements in your template to check first if your has an avatar and if so use it or else use initial_avatars, or make a template tags which would do exactly the same thing in python instead of jinja.
Does this answer your question?

**Comment by kodeine** [comment]
@b0bbywan basically im trying to use it via django rest framework. So i cant use template/jinja.

**Comment by b0bbywan** [comment]
Ok that was my use case too when I developped the app. We chose to let the front (reactJS) do that check, but if you want your API to manage it, I guess you can add a new route and view inspired by the one provided which would check first if your user has an avatar or use initial_avatar.
Basically the idea behind is always the same, but it depends on how you currently use your backend to serve the avatar for the front.

**Comment by kodeine** [comment]
@b0bbywan yea im using angular2 (beta) as a front end. So basically angular needs to check if avatar present if not use the api to generate one? or maybe it will be better to use some angular component to generate the initial avatar?

**Comment by b0bbywan** [comment]
Sorry I won't be able to help you on this since I don't know much about JS outside of vanilla. Just know that the way to generate an initial avatar is simply to call the user's avatar url, so if your user has an avatar in its profile (I guess it's an ImageField), you use this url, if not use the initial_avatar url.
