### ISSUE TITLE
Writing RGBA image into jpeg format throws an error in PILLOW 4.2

### ISSUE THREAD

**Issue by johnyoonh** [axiome-oss/django-initial-avatars#9]
As mentioned in this issue: https://github.com/python-pillow/Pillow/issues/2609

The solution is to either save it in RGB by removing A or save it as PNG
I would think the former solution would make sense, since I haven't seen transparent before. But if this was intentional, maybe you'd like to make this into a setting so that a user can choose.

https://github.com/axiome-oss/django-initial-avatars/blob/f16f438ef7ef2592088b3d342771cf5d3558f045/initial_avatars/generator.py#L202

**Comment by b0bbywan** [comment]
Thanks for the heads up, it's fixed in version 0.9.1
